### ISSUE TITLE
Add ability to allow multiple filenames

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-cli-js#3]
Currently, the command line errors out when trying to use multiple files as the input for a pipe:

`flexio pipes run flexio-docs-assets-upload app-account-navigation.png app-account-password.png app-account-profile.png app-account-region.png app-connections-add.png`

Results in the following:

```
...\flexio-sdk-js\flexio.js:317
                this.sendOneFile(process_eid, callback);
                     ^

TypeError: this.sendOneFile is not a function
    at doCall (C:\Users\dwilliams\AppData\Roaming\npm\node_modules\flexio\node_modules\flexio-sdk-js\flexio.js:317:22)
    at IncomingMessage.<anonymous> (C:\Users\dwilliams\AppData\Roaming\npm\node_modules\flexio\node_modules\flexio-sdk-js\flexio.js:253:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by biwillia** [comment]
Fixed
